version: '2'

services:
    couchbase:
        image: couchbase-todo-app
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
            - 11211:11211
        environment:
            - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
            - COUCHBASE_ADMINISTRATOR_PASSWORD=password
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_PASSWORD=

    spring-boot:
        image: todo-app
        ports:
            - 8080:8080
        environment:
            - COUCHBASE_HOST=couchbase
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_PASSWORD=
        restart: always