version: '2'

services:
    couchbase:
        image: noxob/couchbase-todo-app
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
            - 11211:11211
        environment:
            - CLUSTER_NAME=todocluster
            - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
            - COUCHBASE_ADMINISTRATOR_PASSWORD=password
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_PASSWORD=
            - COUCHBASE_RBAC_USERNAME=admin
            - COUCHBASE_RBAC_PASSWORD=password
            - COUCHBASE_RBAC_NAME=admin

    spring-boot:
        image: noxob/todo-app
        ports:
            - 8080:8080
        environment:
            - COUCHBASE_HOST=couchbase
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_PASSWORD=
        restart: always
    frontend:
        image: noxob/demo-todoapp-ui
        ports:
            - 80:80
        environment:
            - COUCHBASE_HOST=couchbase
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_PASSWORD=
        restart: always